name: Project Tests

on: workflow_dispatch

  # push:
  #   branches:
  #     - main
  #   paths:
  #     - project/**

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change permissions on tests.sh
        run: |
          cd project
          chmod +x tests.sh
      
      - name: Test pipeline
        run:
          ls main
          ./project/tests.sh
