name: Project Tests

# on: workflow_dispatch
on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: Change permissions on tests.sh
        run: |
          chmod +x ./project/tests.sh
      
      - name: Test pipeline
        run:
          ./project/tests.sh
